
export enum SectorName {NONE, ROCKY_TWIN, SANDY_TWIN, TIMBER_HEARTH, BRITTLE_HOLLOW, GIANTS_DEEP, DARK_BRAMBLE, COMET, QUANTUM_MOON, EYE_OF_THE_UNIVERSE};

export enum Frequency {BEACON, QUANTUM, TRAVELER};

export enum Curiosity {VESSEL, TIME_LOOP_DEVICE, QUANTUM_MOON, ANCIENT_PROBE_LAUNCHER};